### DISCUSSION TITLE
Gluco Check shutdown: what's our next step?

### DISCUSSION THREAD

**Discussion by nielsmaerten** [nielsmaerten/gluco-check#185] [Ideas]
In case you haven't heard, Google is shutting down voice-based apps on Assistant.  
Gluco Check will shut down on June 13th, 2023. More info here: https://pages.glucocheck.app/sunset

## So... now what?
I'm not sure, that's why I'm opening this discussion. Ideas are welcome.  

## A possible workaround
Here's an idea I had. Granted it's not fully formed. But maybe we can build from here

* Google is removing all third-party apps from their platform, that much is clear. [Never leave the cult](https://www.amazon.com/Create-Dependency-People-Never-Leave/dp/1530743389).
* So what if we tricked Google into reading our blood sugar from one of its own apps?
* What if we had a service that:
  * whenever our BG is updated in Nightscout
  * the value is updated into an event on Google Calendar with a fixed date?
  * You could say: "Hey Google, what's on my calendar for the 20th of April 1969?"
  * The response would be: "There was 1 entry on that day: at 1:25AM, you had '120 and stable'. "
  * Using Routines, you could even still say: Hey Google, check my sugar. Just map it to the question above.
  * The service should keep the event on that fixed day (4/20/69) updated with every new BG value
 
The best location for a service like this would, I think, be a Nightscout plugin. But I have zero experience writing plugins for that codebase.

What do you think?

**Comment by many7695** [comment]
I really hope u are someone else can find a workaround to get google announce our blood sugars I loved my morning routine find out my schedule weather medication turn on music and especially tell me my current blood sugar, thank u for everything u have done the last few years

**Comment by Atlas-Night-Out** [comment]
two problems now Nightscout server Heroku are starting to charge a high price and this would make it not worth having in the first place for a lot of people, me being one of them. Has for the calendar thing I had this idea a long time ago but it tended to come into difficulties. I'm not the best at code though so maybe you can. I also contacted Google today to give them my mouth too and that was not a nice thing I said to them But I think Google needs to stop doing what they do as they are going to be killing people due to the code within it, which is getting dangerous as we speak! Maybe find a way to do your own api and you might be able to add it to GitHub as this is free! and your software has been a pleasure to use just not the hassles we have through the ones after the money rather than life! Its becoming too much for me to carry on battling them I think of leaving them all to it and save my money for other things. But again its Niightscout and this again causes issues. I will not be paying for another server when I already have one for diabetics! Hope something changes soon and I hope we all can carry on using your bit in the code that google will nick! So like I told them today about the time we sued you google prob why they put the phone down on me. All I want to do is keep alive not have fancy cars and houses! Maybe give Google a call and do a deal with them and tell them you have a App that will effect millions of Diabetic lives put it in writing too and see what they say. They don't know how to do what you have done! I migth also do a big FU GOOGLE and HEROKU on my web site see what they say to that!

**Reply by nielsmaerten** [reply]
I get the frustration. But raging against Google is unlikely to change anything. I think our best option right now is thinking on how to work around this change.

**Comment by BenoitAnastay** [comment]
I did that with HA, my scene is called with a custom trigger, then HA replies with TTS.

It's not a perfect solution since I don't know which speaker ask for BG and it's not the Google TTS 

```yalm
alias: Glycémie
description: ""
trigger:
  - platform: event
    event_type: call_service
    event_data:
      domain: scene
      service: turn_on
      service_data:
        entity_id: scene.glycemie
condition: []
action:
  - service: tts.cloud_say
    data:
      message: >-
        Votre glycémie est a {{ states.sensor.blood_sugar.state}} {% if
        state_attr("sensor.blood_sugar","direction") == "Flat" %}en ligne
        droite{%- elif state_attr("sensor.blood_sugar","direction") ==
        "SingleDown" %}en basse rapide{%- elif
        state_attr("sensor.blood_sugar","direction") == "FortyFiveDown" %}en
        baisse{%- elif state_attr("sensor.blood_sugar","direction") ==
        "DoubleDown" %}en baisse très rapide{%- elif
        state_attr("sensor.blood_sugar","direction") == "SingleUp" %}en montée
        rapide{%- elif state_attr("sensor.blood_sugar","direction") ==
        "FortyFiveUp" %}en montée{%- elif
        state_attr("sensor.blood_sugar","direction") == "DoubleUp" %}en montée
        très rapide{%- endif %}
      entity_id: media_player.googlehome1221
      language: fr-FR
mode: single

```

**Reply by nielsmaerten** [reply]
This looks really cool 🤩! What exactly do you say to trigger the intent? And can you just say it to a Google home, or does it need a speaker connected to a raspi?

I've been looking at Rhasspy and Genie so far. But a solution using 'just' Google hardware would be preferable since 100% of people using GlucoCheck will have had a G-assistant compatible device, Most won't have a HA instance running somewhere.

Nevertheless, congrats on getting this working on HA and (almost) cutting Big G out ;)

**Reply by BenoitAnastay** [reply]
So it does use the Home Automation abilities of Google Home, I mapped an automation scene with the routines of Google Home, when I say "Hey Google, What's my BG", the scene `glycemia` is called on HA, then HA send back a TTS to my Google Home, using the nabu casa TTS service.

The issue is that I can't know which Google Home called the scene, thus I don't know where to route the reply, actually there is only the bedroom speaker that replies.

But the the idea might be perfectible, I'm wondering if there is a way to reply to an Home Automation command with custom text, or less conveinient if we can create one routine/scene combo per speaker so we know where to route the answer

**Comment by ylorig** [comment]
@nielsmaerten have you seen these options (app-actions)? 
https://developer.android.com/guide/app-actions/overview

**Reply by nielsmaerten** [reply]
I did, but unfortunately app actions are not a viable alternative to conversational actions.  
They only work on android devices (phones or tablets) and are very limited. They can trigger some action in an app on your phone in response to a voice command. But they cannot be used to look up info on your nightscout site and read it out to you.

I personally ended up implementing the solution suggested by @BenoitAnastay , and it's working very well for me.  
But I also realize that setting up a complete HomeAssistant server may be way too much effort for someone who just wants Google to read out their blood sugar.

**Reply by Tek420** [reply]
OY!  So my config for your app broke a few months ago and I finally put the time in and went with the Nightscout Pro site all so I could get my GlucoCheck working again on my Google devices!  What a bummer to find Google is killing this awesome app!  It has saved me a ton of times when I can barely wake up to get my BG read out loud and not have to fumble with the pump, lights, glasses, etc.

So question, I have a HA instance running on a Pi but I do not see how @BenoitAnastay is getting the data into HA to be able to spit out the details.  Do you have any insight on that which may help me figure it out?  I am nit sure I see it in there even after translating the French.

If not no worries and please, truly from the bottom of my heart, thanks so much for doing the original app.  I really used it a lot and you definitely were one of the underappreciated things I used daily to keep on top of my BG.  I guess you never appreciate the good things until they are gone or soon to be so!

Dave

**Reply by nielsmaerten** [reply]
Hi @Tek420  
Thanks for these kind words! 😊

I'm using the Nightscout integration for HA: https://www.home-assistant.io/integrations/nightscout  
Once you've set this up, you'll have an entity in HA called `sensor.blood_sugar` that you can use to trigger automations.  
Here's mine: it plays an alert on all speakers using the TTS service if my sugar drops below 70mg/dl for 15 minutes:

```yaml
alias: 🩸 Blood sugar low => Play alerts
description: "Plays an alert on all speakers if my BG falls below 70 for more than 15 minutes. During the night, it also turns on the bedroom lights."
# Trigger when BG is <70 for 15m
trigger:
  - platform: numeric_state
    entity_id: sensor.blood_sugar
    for:
      hours: 0
      minutes: 15
      seconds: 0
    below: 70
# Don't do anything if I'm not home
condition:
  - condition: zone
    entity_id: person.niels
    zone: zone.home
action:
# If it is night...
  - if:
      - condition: sun
        after: sunset
        before: sunrise
    then:
# ... then turn on the bedroom lights
      - service: scene.turn_on
        target:
          entity_id: scene.bedroom_dimmed
        metadata: {}
# Repeat the warning message 3 times
  - repeat:
      count: "3"
      sequence:
        - service: tts.google_translate_say
          data:
            entity_id: media_player.all_speakers
            message: Warning: blood sugar is low. Drink a juicebox; right now!
            language: en
            cache: false
        - delay:
            hours: 0
            minutes: 0
            seconds: 20
            milliseconds: 0
mode: single

```

Second, if you create a script in HomeAssistant, you can call if from a Google Home as if it were a scene.  
So for the following script, if you say "Hey Google, activate Glucose Check"... it will read out your sugar to all speakers:
```yaml
alias: Glucose Check
sequence:
  - service: tts.google_translate_say
    data:
      cache: false
      entity_id: media_player.all_speakers
# This is the template that pulls the value from the sensor, and reads it out in the message:
      message: Blood sugar is currently {{ states('sensor.blood_sugar') }}
mode: single

```
Finally,
To get Google to activate scenes in HA, you'll have to add HA as a service in your Google Home app.  
The easiest way to do this (but not free) is by using Nabu Casa: https://www.nabucasa.com/config/google_assistant/

It's also possible to set this up yourself, but this requires a bit more work. Instructions are here: https://www.home-assistant.io/integrations/google_assistant/

---
Hope this helps! Thanks for using Gluco Check all this time. Building it has been a ton of fun.  
But... as with all things from Google... they ultimately must end up on https://killedbygoogle.com 🥲
